[package]
name    = "miri"
version.workspace = true
edition.workspace = true

[dependencies]
sharc.workspace   = true
colored.workspace = true
logger            = { path = "../logger" }
libffi = "4.1"
