[package]
name    = "sharc-cli"
version.workspace = true
edition.workspace = true

[dependencies]
colored.workspace = true
sharc             = { path = "../sharc" }
miri              = { path = "miri" }

[features]
backtrace = ["sharc/backtrace"]

[[bin]]
name = "sharc"
path = "src/main.rs"
